<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.AI.OpenAI" Version="2.2.0-beta.2" />
      <PackageReference Include="Azure.Data.AppConfiguration" Version="1.5.0" />
      <PackageReference Include="Google.Protobuf" Version="3.30.0-rc1" />
      <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
      <PackageReference Include="Grpc.Tools" Version="2.70.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.42.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="8.1.0-preview" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
      <PackageReference Include="MongoDB.Driver" Version="3.2.1" />
      <PackageReference Include="NAudio" Version="2.2.1" />
      <PackageReference Include="OpenAI" Version="2.2.0-beta.2" />
      <PackageReference Include="PromptCompose" Version="0.0.1-development" />
      <PackageReference Include="PromptCompose.Robotics" Version="0.0.1-development" />
      <PackageReference Include="Spectre.Console" Version="0.49.2-preview.0.75" />
      <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

    
    <ItemGroup>
        <Protobuf Include="Services\FaceIdentificationService.proto" GrpcServices="Client" />
        <Protobuf Include="Services\AudioIdentificationService.proto" GrpcServices="Client" />
    </ItemGroup>
</Project>
